### PR TITLE
Export CodatApiClient

### PR DESCRIPTION
**Pull request by Hawk94**
Export the CodatAPIClient explicitly allowing it to be used directly.

### CODE REVIEW

**Comment by christopherdcunha** [comment]
Instead of this PR, would you be able export `CodatApiClient`?

**Comment by jasond-s** [comment]
@Hawk94 I am inclined to agree with @christopherdcunha here. This is really a helper around interacting with the codat API and adding a proxy environment and subtly, but fundamentally, changing the meaning of the `apiKey` in the base `class Api` is not ideal. Exposing the actual class that does the work sounds ok though, and it's less code 😛 .

**Comment by Hawk94** [comment]
@jasond-s I agree - have amended this PR to export the CodatAPIClient, it would be great if you could review/merge 😄

**Comment by jasond-s** [comment]
Looks good. Thanks guys!

**Comment by jasond-s** [comment]
Will get that published ASAP.

**Pull request merged**
